########################################
##### Network landscape generation #####
########################################

# Figure 5A is generated by Cytoscape
###### Input: BioGRID_edges_all.txt: Processed data from BioGRID v3.5.183 (Available at Evaluation_processing folder DORGE_pipeline project https://github.com/biocq/DORGE_pipeline)
###### Input: nodes_anno.txt: Processed data from BioGRID v3.5.183 (Generated by this file; Available at Evaluation_processing folder DORGE_pipeline project https://github.com/biocq/DORGE_pipeline)
###### Internal: data/BioGRID/BioGRID_Cytoscape_session.cys: Cytoscape session (Also available at Evaluation_processing folder DORGE_pipeline project https://github.com/biocq/DORGE_pipeline)
###### Output: Figure_5A_BioGRID_network_landscape.png: PPI landscape generated by Cytoscape


# Figure 5B is generated by Metascape (https://metascape.org/gp/index.html)
###### Input: DORGE-predicted TSG/OG lists (Available at data/Metascape/metascape_input_genes.xlsx)
###### Internal: MCODE_PPI.cys: Cytoscape session generated by Metascape (Original name: _FINAL_MCODE_ALL_PPIColorByCounts.pdf when downloaded from Metascape)
###### Output: Figure_5B_PPI_MCODE_modules.pdf: PPI modules generated by the Cytoscape session


options(warn=-1)

### Install missing packages

installed_pkgs <- installed.packages()

pkgs <-  c("plyr","ggpubr","ggplot2")


if (length(setdiff(pkgs, installed_pkgs)) > 0) {
    install.packages(pkgs = setdiff(pkgs, installed_pkgs))
}

library("ggpubr")
library(plyr)

TSG_threshold<-0.62485 #loose FPR=0.01
OG_threshold<-0.7004394 #loose FPR=0.01

#TSG_threshold<-0.8290429 #strict FPR=0.005
#OG_threshold<-0.8679444 #strict FPR=0.005
##################### Figure 5A: PPI network node annotation generation #####################

#setwd("/Users/jlyu/Box\ Sync/TSGOG_Project/SA_sub/github/DORGE_paper/Figure_codes/Figure_5");
anno <- read.table("../Gene_set_new.txt", header=T, sep="\t",fill=TRUE,quote = "")
colnames(anno)<-c("Gene","TSG_core","OG_core","NG","TSG_all","OG_all");
prediction <- read.table("../DORGE_prediction.txt", header=T, sep="\t",fill=TRUE,quote = "")
anno<-cbind(anno[,c(1,4,5,6)],prediction[,2:5])
all_feature <- read.table("data/BioGRID/BioGRID_edges_all.txt", header=T, sep="\t",fill=TRUE,quote = "")
Genes<-unique(c(as.character(all_feature$Gene1),as.character(all_feature$Gene2)))
Gene_type<-rep("",length(Genes))
combined<-data.frame(Gene=Genes,Gene_type=Gene_type)
combined$Gene_type<-as.character(combined$Gene_type)
join<-join(combined, anno,type = "left",by="Gene")
index_NG<-which(join$NG=="1")
index_pOG<-which(join$OG_probability> OG_threshold & join$TSG_probability<TSG_threshold & join$OG_all!="1")
index_pTSG<-which(join$TSG_probability>TSG_threshold & join$OG_probability< OG_threshold & join$TSG_all!="1")
index_TSG<-which(join$TSG_all=="1" & join$OG_all!="1")
index_OG<-which(join$OG_all=="1" & join$TSG_all!="1")
index_pdual<-which((join$OG_all=="1" & join$TSG_all!="1" & join$TSG_probability>TSG_threshold)|(join$TSG_all=="1" & join$OG_all!="1" & join$OG_probability>OG_threshold)|(join$TSG_all!="1" & join$OG_all!="1" & join$TSG_probability>TSG_threshold & join$OG_probability>OG_threshold))
index_dual<-which(join$OG_all=="1" & join$TSG_all=="1")

join$Gene_type[join$Gene_type==""]<-"Other"
join$Gene_type[index_NG]<-"NG"
join$Gene_type[index_TSG]<-"CGC-TSG"
join$Gene_type[index_OG]<-"CGC-OG"
join$Gene_type[index_pOG]<-"Novel DORGE-OG"
join$Gene_type[index_pTSG]<-"Novel DORGE-TSG"
join$Gene_type[index_pdual]<-"Novel DORGE-Dual"
join$Gene_type[index_dual]<-"CGC-dual"

join<-join[,c("Gene","Gene_type")]
write.table(join,"data/BioGRID/nodes_anno.txt",sep="\t",quote=F,row.names=F,col.names=T)


##################### Statistical test related to Figure 5B: Statistical signficance calculation for dual function genes in the PPI network module #####################

#setwd("/Users/jlyu/Box\ Sync/TSGOG_Project/SA_sub/github/DORGE_paper/Figure_codes/Figure_5");
anno <- read.table("../Gene_set_new.txt", header=T, sep="\t",fill=TRUE,quote = "")
colnames(anno)<-c("Gene","TSG_core","OG_core","NG","TSG_all","OG_all");
prediction <- read.table("../DORGE_prediction.txt", header=T, sep="\t",fill=TRUE,quote = "")
anno<-cbind(anno[,c(1,4,5,6)],prediction[,2:3])

index<-rep("Other",nrow(anno))
index_NG<-which(anno$NG=="1")
index_pOG<-which(anno$OG_probability> OG_threshold & anno$TSG_probability<TSG_threshold & anno$OG_all!="1")
index_pTSG<-which(anno$TSG_probability>TSG_threshold & anno$OG_probability< OG_threshold & anno$TSG_all!="1")
index_TSG<-which(anno$TSG_all=="1" & anno$OG_all!="1")
index_OG<-which(anno$OG_all=="1" & anno$TSG_all!="1")
index_pdual<-which((anno$OG_all=="1" & anno$TSG_all!="1" & anno$TSG_probability>TSG_threshold)|(anno$TSG_all=="1" & anno$OG_all!="1" & anno$OG_probability> OG_threshold)|(anno$TSG_all!="1" & anno$OG_all!="1" & anno$TSG_probability>TSG_threshold & anno$OG_probability> OG_threshold))

index_dual<-which(anno$OG_all=="1" & anno$TSG_all=="1")

index[index_NG]<-"NG"
index[index_pOG]<-"Novel DORGE-OG"
index[index_pTSG]<-"Novel DORGE-TSG"
index[index_TSG]<-"CGC-TSG"
index[index_OG]<-"CGC-OG"
index[index_pdual]<-"Novel DORGE-dual"
index[index_dual]<-"CGC-dual"

index_DORGE_predicted_nonCGC_OG<-which(anno$OG_probability> OG_threshold & anno$OG_all!="1")
index_DORGE_predicted_nonCGC_TSG<-which(anno$TSG_probability>TSG_threshold & anno$TSG_all!="1")

index_novel_TSG_specific<-setdiff(index_DORGE_predicted_nonCGC_TSG,index_DORGE_predicted_nonCGC_OG)
index_novel_OG_specific<-setdiff(index_DORGE_predicted_nonCGC_OG,index_DORGE_predicted_nonCGC_TSG)
#write.table(anno[index_novel_TSG_specific,c(1,5)],"data/DORGE_predicted_CGC_TSGs_scores.txt",sep="\t",quote=F,row.names=F,col.names=T)
#write.table(anno[index_novel_OG_specific,c(1,6)],"data/DORGE_predicted_CGC_OGs_scores.txt",sep="\t",quote=F,row.names=F,col.names=T)


index_DORGE_predicted_CGC_OG<-which(anno$OG_probability>OG_threshold & anno$OG_all=="1")
index_DORGE_predicted_CGC_TSG<-which(anno$TSG_probability>TSG_threshold & anno$TSG_all=="1")
#write.table(as.character(anno[index_DORGE_predicted_CGC_TSG,1]),"data/DORGE_predicted_CGC_TSGs.txt",sep="\t",quote=F,row.names=F,col.names=F)
#write.table(as.character(anno[index_DORGE_predicted_CGC_OG,1]),"data/DORGE_predicted_CGC_OGs.txt",sep="\t",quote=F,row.names=F,col.names=F)

index_DORGE_predicted_OG<-which(anno$OG_probability>OG_threshold)
index_DORGE_predicted_TSG<-which(anno$TSG_probability>TSG_threshold)
length(index_DORGE_predicted_OG)#669
length(index_DORGE_predicted_TSG)#968
index_DORGE_predicted_driver_genes<-union(index_DORGE_predicted_TSG,index_DORGE_predicted_OG)
length(index_DORGE_predicted_driver_genes)#1201
#write.table(as.character(anno[index_DORGE_predicted_driver_genes,1]),"data/DORGE_predicted_drivers.txt",sep="\t",quote=F,row.names=F,col.names=F)

index_DORGE_predicted_CGC_driver_genes<-union(index_DORGE_predicted_CGC_TSG,index_DORGE_predicted_CGC_OG)
length(index_DORGE_predicted_CGC_driver_genes)#328

index_dual_driver<-which(index=="CGC-dual" | index=="Novel DORGE-dual")
length(index_dual_driver)#480
index_DORGE_predicted_CGC_dual_driver<-intersect(which(index=="CGC-dual"),intersect(index_DORGE_predicted_CGC_TSG,index_DORGE_predicted_CGC_OG))
length(index_DORGE_predicted_CGC_dual_driver)#43

index_DORGE_predicted_CGC_dual_driver_genes<-intersect(index_DORGE_predicted_driver_genes,index_dual_driver)
length(index_DORGE_predicted_CGC_dual_driver_genes)#461

#The probability of the predicted novel dual function gene occurence in the modules
binom.test(90,90,p=length(index_DORGE_predicted_dual_driver_genes)/1201)$p.value # 3.751566e-38


#The probability of the CGC-dual function gene occurence in the modules
binom.test(14,90,p=length(index_DORGE_predicted_CGC_dual_driver)/1201)$p.value #3.949327e-06


#write.table(as.character(anno[union(which(anno$OG_probability> OG_threshold),which(anno$TSG_probability> TSG_threshold)),1]),"DORGE_predicted_driver_genes.txt",sep="\t",quote=F,row.names=F,col.names=F)
