########################################
##### Network landscape generation #####
########################################

# Figure 5A is generated by Cytoscape
###### Input: BioGRID_edges_all.txt: Processed data from BioGRID v3.5.183 (Available at Evaluation_processing folder DORGE_pipeline project https://github.com/biocq/DORGE_pipeline)
###### Input: nodes_anno.txt: Processed data from BioGRID v3.5.183 (Available at Evaluation_processing folder DORGE_pipeline project https://github.com/biocq/DORGE_pipeline)
###### Internal: data/BioGRID/BioGRID_Cytoscape_session.cys: Cytoscape session (Also available at Evaluation_processing folder DORGE_pipeline project https://github.com/biocq/DORGE_pipeline)
###### Output: Figure_5A_BioGRID_network_landscape.png: PPI landscape generated by Cytoscape


# Figure 5B is generated by Metascape (https://metascape.org/gp/index.html)
###### Input: DORGE-predicted TSG/OG lists (Available at data/Metascape/metascape_input_genes.xlsx)
###### Internal: MCODE_PPI.cys: Cytoscape session generated by Metascape (Original name: _FINAL_MCODE_ALL_PPIColorByCounts.pdf when downloaded from Metascape)
###### Output: Figure_5B_PPI_MCODE_modules.pdf: PPI modules generated by the Cytoscape session


options(warn=-1)

installed_pkgs <- installed.packages()

pkgs <-  c("plyr")

if (length(setdiff(pkgs, installed_pkgs)) > 0) {
    install.packages(pkgs = setdiff(pkgs, installed_pkgs), repos = "http://cran.us.r-project.org")
}

suppressMessages(library(plyr))

TSG_threshold<-0.6233374 #FPR=0.01
OG_threshold<-0.6761319 #FPR=0.01

##################### Figure 5A: PPI network node annotation generation #####################

#setwd("/Users/jlyu/Box\ Sync/TSGOG_Project/SA_sub/github/DORGE_paper/DORGE_codes/Figure_5");

##################### Statistical test related to Figure 5B: Statistical signficance calculation for dual function genes in the PPI network module #####################

#setwd("/Users/jlyu/Box\ Sync/TSGOG_Project/SA_sub/github/DORGE_paper/DORGE_codes/Figure_5");
anno <- read.table("../Gene_set_new.txt", header=T, sep="\t",fill=TRUE,quote = "")
colnames(anno)<-c("Gene","TSG_core","OG_core","NG","TSG_all","OG_all");
prediction <- read.table("../DORGE_prediction.txt", header=T, sep="\t",fill=TRUE,quote = "")
anno<-cbind(anno[,c(1,4,5,6)],prediction[,2:3])

index<-rep("Other",nrow(anno))
index_NG<-which(anno$NG=="1")
index_pOG<-which(anno$OG_probability> OG_threshold & anno$TSG_probability<TSG_threshold & anno$OG_all!="1")
index_pTSG<-which(anno$TSG_probability>TSG_threshold & anno$OG_probability< OG_threshold & anno$TSG_all!="1")
index_TSG<-which(anno$TSG_all=="1" & anno$OG_all!="1")
index_OG<-which(anno$OG_all=="1" & anno$TSG_all!="1")
index_pdual<-which((anno$OG_all=="1" & anno$TSG_all!="1" & anno$TSG_probability>TSG_threshold)|(anno$TSG_all=="1" & anno$OG_all!="1" & anno$OG_probability> OG_threshold)|(anno$TSG_all!="1" & anno$OG_all!="1" & anno$TSG_probability>TSG_threshold & anno$OG_probability> OG_threshold))

index_dual<-which(anno$OG_all=="1" & anno$TSG_all=="1")

index[index_NG]<-"NG"
index[index_pOG]<-"Novel DORGE-OG"
index[index_pTSG]<-"Novel DORGE-TSG"
index[index_TSG]<-"CGC-TSG"
index[index_OG]<-"CGC-OG"
index[index_pdual]<-"Novel DORGE-dual"
index[index_dual]<-"CGC-dual"

index_DORGE_predicted_nonCGC_OG<-which(anno$OG_probability> OG_threshold & anno$OG_all!="1")
index_DORGE_predicted_nonCGC_TSG<-which(anno$TSG_probability>TSG_threshold & anno$TSG_all!="1")

index_novel_TSG_specific<-setdiff(index_DORGE_predicted_nonCGC_TSG,index_DORGE_predicted_nonCGC_OG)
index_novel_OG_specific<-setdiff(index_DORGE_predicted_nonCGC_OG,index_DORGE_predicted_nonCGC_TSG)
#write.table(anno[index_novel_TSG_specific,c(1,5)],"data/DORGE_predicted_CGC_TSGs_scores.txt",sep="\t",quote=F,row.names=F,col.names=T)
#write.table(anno[index_novel_OG_specific,c(1,6)],"data/DORGE_predicted_CGC_OGs_scores.txt",sep="\t",quote=F,row.names=F,col.names=T)


index_DORGE_predicted_CGC_OG<-which(anno$OG_probability>OG_threshold & anno$OG_all=="1")
index_DORGE_predicted_CGC_TSG<-which(anno$TSG_probability>TSG_threshold & anno$TSG_all=="1")
write.table(as.character(anno[index_DORGE_predicted_CGC_TSG,1]),"data/DORGE_predicted_CGC_TSGs.txt",sep="\t",quote=F,row.names=F,col.names=F)
write.table(as.character(anno[index_DORGE_predicted_CGC_OG,1]),"data/DORGE_predicted_CGC_OGs.txt",sep="\t",quote=F,row.names=F,col.names=F)

index_DORGE_predicted_OG<-which(anno$OG_probability>OG_threshold)
index_DORGE_predicted_TSG<-which(anno$TSG_probability>TSG_threshold)
length(index_DORGE_predicted_OG)#683
length(index_DORGE_predicted_TSG)#925
index_DORGE_predicted_driver_genes<-union(index_DORGE_predicted_TSG,index_DORGE_predicted_OG)
length(index_DORGE_predicted_driver_genes) #DORGE predicted driver genes: 1172
write.table(as.character(anno[index_DORGE_predicted_driver_genes,1]),"data/DORGE_predicted_drivers.txt",sep="\t",quote=F,row.names=F,col.names=F)

index_DORGE_predicted_CGC_driver_genes<-union(index_DORGE_predicted_CGC_TSG,index_DORGE_predicted_CGC_OG)
length(index_DORGE_predicted_CGC_driver_genes)#325

index_dual_driver<-which(index=="CGC-dual" | index=="Novel DORGE-dual")
length(index_dual_driver)#477
index_DORGE_predicted_CGC_dual_driver<-intersect(which(index=="CGC-dual"),intersect(index_DORGE_predicted_CGC_TSG,index_DORGE_predicted_CGC_OG))
length(index_DORGE_predicted_CGC_dual_driver)#43

index_DORGE_predicted_dual_driver_genes<-intersect(index_DORGE_predicted_driver_genes,index_dual_driver)
length(index_DORGE_predicted_dual_driver_genes)#457

#The probability of the predicted novel dual function gene occurence in the modules
binom.test(64,64,p=length(index_DORGE_predicted_dual_driver_genes)/length(index_DORGE_predicted_driver_genes))$p.value # 6.656864e-27

#The probability of the CGC-dual function gene occurence in the modules
binom.test(8,64,p=length(index_DORGE_predicted_CGC_dual_driver)/length(index_DORGE_predicted_driver_genes))$p.value # 0.002325191


#write.table(as.character(anno[union(which(anno$OG_probability> OG_threshold),which(anno$TSG_probability>TSG_threshold)),1]),"DORGE_predicted_driver_genes.txt",sep="\t",quote=F,row.names=F,col.names=F)
