########################################
##### Network landscape generation #####
########################################

# Figure is generated by Cytoscape

###### Input data are available at Evaluation_processing folder DORGE_pipeline project https://github.com/biocq/DORGE_pipeline
###### Input: drug_gene_nr.txt: Processed data from PharmacoDB database (Generated from folder Evaluation/PharmacoDB/)
###### Input: nodes_anno.txt: Gene annotation file (Generated by this file, in folder Evaluation/PharmacoDB/)

###### Internal: data/PharmacoDB/PharmacoDB/PharmacoDB_Cytoscape_session.cys: Cytoscape session

###### Output: Figure_S5D_PharmacoDB_landscape.png: Gene-compound network landscape generated by Cytoscape, generated by the Cytoscape session